SELECT 
    TO_CHAR(S.SALES_DATE,'yyyy') YEAR
    , EXTRACT(MONTH FROM S.SALES_DATE) MONTH
    , U.GENDER GENDER
    , COUNT(DISTINCT U.USER_ID) USERS
FROM 
    ONLINE_SALE S
    , USER_INFO U
WHERE 
    S.USER_ID = U.USER_ID
    AND GENDER IS NOT NULL
GROUP BY 
    TO_CHAR(S.SALES_DATE,'yyyy')
    , EXTRACT(MONTH FROM S.SALES_DATE)
    , U.GENDER
ORDER BY 1, 2, 3
;
