SELECT
    I.ANIMAL_ID
    , I.ANIMAL_TYPE
    , I.NAME
FROM 
    ANIMAL_INS I
    , ANIMAL_OUTS O
WHERE
    I.ANIMAL_ID = O.ANIMAL_ID -- join
    AND SEX_UPON_INTAKE LIKE 'Intact%'
    AND SEX_UPON_INTAKE != SEX_UPON_OUTCOME
    -- AND (SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%')
;
