SELECT A.AUTHOR_ID, A.AUTHOR_NAME, SALE_SUM.CATEGORY, SALE_SUM.TOTAL_SALES
FROM 
    (
    SELECT AUTHOR_ID, B.CATEGORY, SUM(S.SALES*PRICE) TOTAL_SALES
    FROM 
        BOOK_SALES S
        INNER JOIN BOOK B USING(BOOK_ID)
    WHERE TO_CHAR(S.SALES_DATE,'yyyymm') = '202201'
    GROUP BY AUTHOR_ID, B.CATEGORY
    ) SALE_SUM
    INNER JOIN AUTHOR A USING(AUTHOR_ID)
ORDER BY 1 ASC, 3 DESC
;
