SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, to_char(R.CREATED_DATE, 'yyyy-mm-dd')
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE B.BOARD_ID = R.BOARD_ID
    AND B.CREATED_DATE BETWEEN TO_DATE(20221001,'yyyymmdd') AND TO_DATE(20221031,'yyyymmdd')
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC
;
