SELECT JULY_SUM.FLAVOR
FROM
    (
        SELECT FLAVOR, SUM(TOTAL_ORDER) SUM1
        FROM JULY
        GROUP BY FLAVOR
    ) JULY_SUM
    ,(
        SELECT FLAVOR, SUM(TOTAL_ORDER) SUM2
        FROM FIRST_HALF
        GROUP BY FLAVOR
    ) FIRST_HALF_SUM
WHERE JULY_SUM.FLAVOR = FIRST_HALF_SUM.FLAVOR
ORDER BY SUM1+SUM2 DESC
FETCH FIRST 3 ROWS ONLY
;

-- SELECT FLAVOR
-- FROM
--     (
--         SELECT *
--         FROM JULY
--         UNION ALL
--         SELECT *
--         FROM FIRST_HALF
--     ) A
-- GROUP BY FLAVOR
-- ORDER BY SUM(TOTAL_ORDER) DESC
-- LIMIT 3
-- ;
